### PR TITLE
DiscordRPC Enhance

### PR DESCRIPTION
**Pull request by Lukwrs**
play game NFS

### CODE REVIEW

**Comment by GitMensch** [comment]
@metonator is this PR still considered to be "active"? Is it still reasonable to have this fork (after the PR is closed) as the work seems to be done in https://github.com/worldunitedgg/GameLauncher_NFSW solely now?

**Comment by metonator** [comment]
this PR was never active, and since i've moved this code to another location, sbrw devs decided to create a fork from new location. (and yea, i cant close this PR)

**Comment by GitMensch** [comment]
Is it still reasonable to have this fork? Otherwise I'd suggest to delete the repository (on the "settings") or at least make it read-only after adjusting README to point people to the right place.

**Comment by GitMensch** [comment]
@LeoCodes21 Seems like you're the right one to close his PR/delete the repo (or at least make it read-only), correct?

**Pull request closed without merging**
