### PR TITLE
Update RichPresenceAssets

### PR DESCRIPTION
**Pull request by Zacam**
Size Optimize for Discord Rendering (512x512 is excessive for a 48x48 space) on the Avatars; Data Optimize by removing unused Alpha Channel.

Update Event Icons overlay for Size, 512x512 is overkill for a 12x12 rendering space.

Added missing "default" avatar_26 from original game files (NFSW "N" Logo)

ToDo: Co-Ordinate between WorldUnited and WorldEvolved for avatars_27+ to prevent overlap so that all can be rendered/supplied to RPC.

### CODE REVIEW

**Comment by Zacam** [comment]
To note: WEv2 currently has avatars in 27-40, WU is using 26-31 (since it is missing the original LG_DRIVER26 image). This may also be a more complicated issue if additional servers opt for custom avatars.bin delivery as it will break presentation format on Discord without RichPresenceAssets updates (unless they can be supplied by the given server directly)

**Comment by ghost** [comment]
>ToDo: Co-Ordinate between WorldUnited and WorldEvolved for avatars_27+ to prevent overlap so that all can be rendered/supplied to RPC.

This is already done, every server creator can supply their Discord Application ID (like WUGG, WOPL, and NR) to get their assets loaded and managed without issues.

**Comment by Zacam** [comment]
Then why isn't it working to display that servers Custom Avatars, have they just not loaded them where they need to be? None of the WU Donor custom avatars (in Avatars.bin 26-31) will display on Discord RPC, which is why I was under the impression they needed to be added to the RichPresenceAssets folder; which is when I discovered the filename overlap between it an WEv2.

**Comment by ghost** [comment]
> Then why isn't it working to display that servers Custom Avatars, have they just not loaded them where they need to be? None of the WU Donor custom avatars (in Avatars.bin 26-31) will display on Discord RPC, which is why I was under the impression they needed to be added to the RichPresenceAssets folder; which is when I discovered the filename overlap between it an WEv2.

Thats correct, they didnt supplied assets to discord developers dashboard (yet). That's why only WOPL has them atm

**Comment by ghost** [comment]
--UPDATE:--
However, assets must stay 512x512 as minimum according to Discord Developers Dashboard:
Screenshot_20200614_123826_com android chrome

**Comment by Zacam** [comment]
JFC, -Discord- is enforcing that they have to be 512x512?
Lovely. Aight then.I'll update the #26 one to 512 then.

**Pull request merged**
